### ISSUE TITLE
The ROM Simulation 1D Solver INPUT FILE FORMAT SEGMENT documentation is wrong

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/simvascular.github.io#12]
### Description

The ROM Simulation 1D Solver INPUT FILE FORMAT SEGMENT documentation states that 
```
Outlet boundary condition types

FLOW - Time-varying outlet flow rate.

NOBOUND - No outlet boundary condition; used for internal segment outlets.

RCR - Boundary condition specified through an RCR circuit.

RESISTANCE - Constant resistance in model units.
```

The `FLOW` boundary condition is in fact not supported.

### Reproduction

Specify a `SEGMENT` with a `FLOW` outlet boundary condition type.

### Expected behavior

I expect the documentation to be correct.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by ktbolt** [comment]
@JonathanPham Please update the SV web documentation for the 1D solver, seems to be missing coronary BCs, stenosis modeling, etc.

**Comment by JonathanPham** [comment]
I haven't worked much with the 1D solver, so I don't think I am the right person to update the documentation here. @mrp089 can you take a look at this or recommend someone who has more experience with the 1D solver?

Also, seems like this issue is related to #4.

**Comment by mrp089** [comment]
Where is that text that you're quoting, @ktbolt?

**Comment by mrp089** [comment]
Got it!
