### ISSUE TITLE
Move 0D documentation to svZeroDPlus

### ISSUE THREAD

**Issue by mrp089** [SimVascular/simvascular.github.io#14]
### Problem

See https://github.com/StanfordCBCL/svZeroDPlus/issues/58. This documentation and the one in `svZeroDPlus` diverged a while ago due to the difficulty of keeping two repositories up to date.

### Solution

We already have added [documentation](https://stanfordcbcl.github.io/svZeroDPlus/) to 0D+ in the Doxygen-generated HTML files, including the linear system, time integration, and 0D blocks. Once  https://github.com/StanfordCBCL/svZeroDPlus/pull/57 is merged, I'll remove the folder `documentation/rom_simulation/0d-solver` and point all 0D references to https://stanfordcbcl.github.io/svZeroDPlus/ 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by mrp089** [comment]
This is analog to #9

**Comment by ktbolt** [comment]
@mrp089 Do you mean remove the 0D solver documentation from the SV website?

 If so then that is not going to happen.

**Comment by mrp089** [comment]
@menon-karthik: @ktbolt and I came up with an alternative to deleting the 0D documentation: I'll prototype a new documentation that outlines the 0D solver and links to specific parts in the Doxygen to guide users more through it. This way users still have some guidance but we don't need to duplicate documentation like schematics, equations, and matrices.

Input welcome! Depending on how this goes, we can think about how to handle the documentation for `svFSI+`.
