### ISSUE TITLE
Add svFSIplus documentation

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/simvascular.github.io#19]
### Use Case

It would be helpful to users to  have documentation describing how to use svFSIplus.

### Problem

There is no svFSIplus documentation. 

### Solution

 Write svFSIplus documentation.

### Alternatives considered

Don't write svFSIplus documentation.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by ktbolt** [comment]
I am going to start on this. 

@alisonmarsden Should I remove the svFSI documentation?

**Comment by alisonmarsden** [comment]
Yes ok to remove old documentation as soon as new docs are available.  Eventually we should also remove svSolver docs as well.

---------------------------------------------------------------
Alison Marsden, PhD (she / her)
Douglass M. and Nola Leishman Professor of Cardiovascular Disease
Professor of Pediatrics and Bioengineering, and by courtesy of Mechanical Engineering
Institute for Computational and Mathematical Engineering
Stanford University
https://cbcl.stanford.edu/
www.simvascular.org<http://www.simvascular.org>
Co-Director CHIP T32 Program
https://med.stanford.edu/cvi/education/chip-t32.html#appl


From: Dave Parker ***@***.***>
Date: Saturday, May 11, 2024 at 2:11 PM
To: SimVascular/simvascular.github.io ***@***.***>
Cc: Alison Lesley Marsden ***@***.***>, Mention ***@***.***>
Subject: Re: [SimVascular/simvascular.github.io] Add svFSIplus documentation (Issue #19)

I am going to start on this.

@alisonmarsden<https://github.com/alisonmarsden> Should I remove the svFSI documentation?

**Comment by ktbolt** [comment]
I've taken the svFSI docs and reorganized them for svFSIplus, not sure of the final format yet.
<img width="1534" alt="Screenshot 2024-05-30 at 8 46 35 PM" src="https://github.com/SimVascular/simvascular.github.io/assets/23109458/04b7d55d-aaf8-4dad-a46c-df0431e73536">

**Comment by ktbolt** [comment]
I am also experimenting with documenting the solver input XML file by showing the XML element name, type and a link (blue) to the parameter definition. 


<img width="1528" alt="Screenshot 2024-05-30 at 9 21 06 PM" src="https://github.com/SimVascular/simvascular.github.io/assets/23109458/c355b09f-94cf-4c87-9db2-00ba7d025653">

**Comment by ktbolt** [comment]
I've added more solver input XML file documentation: mesh, equation, linear solver and boundary condition parameters
<img width="1372" alt="Screenshot 2024-06-19 at 7 49 42 PM" src="https://github.com/SimVascular/simvascular.github.io/assets/23109458/be27abaf-d873-48ee-b3bd-542086c44148">

I am currently documenting parameters in two sections

1) XML format
<img width="807" alt="Screenshot 2024-06-19 at 7 53 28 PM" src="https://github.com/SimVascular/simvascular.github.io/assets/23109458/9988ced6-aed1-457f-82df-2be422a2caf5">


2) Description
<img width="1040" alt="Screenshot 2024-06-19 at 7 53 43 PM" src="https://github.com/SimVascular/simvascular.github.io/assets/23109458/78f8937e-6703-4013-925b-32d68170b22c">


clicking on the blue XML format moves the page to that parameter's description.

I thought this would help show the XML structure better because it can have nested sections. 
<img width="1045" alt="Screenshot 2024-06-19 at 8 02 23 PM" src="https://github.com/SimVascular/simvascular.github.io/assets/23109458/11aa9f18-5184-499a-82b6-8e09e59319ad">



But maybe having the XML format and description together would be better.

**Comment by ktbolt** [comment]
I've changed the parameter format to have the XML format and description together 

<img width="1361" alt="Screenshot 2024-06-21 at 6 54 02 PM" 
src="https://github.com/SimVascular/simvascular.github.io/assets/23109458/69ffb705-5490-4a87-ae4b-3bc1face7074">

This is super tedious to write but I think it works better.

**Comment by ktbolt** [comment]
I've mostly finished the XML parameter documentation, still a bunch of parameters that are not documented, no definitions in the svFSI `svFSI_master.inp` file.

**Comment by ktbolt** [comment]
I'm now writing a `Running svFSI` section to explain element types and node ordering, VTK mesh files, BC data files formats, etc.

**Comment by ktbolt** [comment]
I've added most of the FSI Tool documentation, still need to add some of the parameter descriptions though.
<img width="985" alt="Screenshot 2024-07-12 at 6 57 18 PM" src="https://github.com/user-attachments/assets/39c3513f-fc84-4a2c-b85f-76dffac53922">

**Comment by ktbolt** [comment]
I've added a `Tutorial` for setting up a fluids simulation.
<img width="1360" alt="Screenshot 2024-07-18 at 11 55 50 AM" src="https://github.com/user-attachments/assets/5175060b-b308-4765-96a6-a44835bcd56e">

**Comment by ktbolt** [comment]
I've added a rough `User Guide` section taking material from the svFSI documentation
<img width="1289" alt="Screenshot 2024-07-18 at 6 24 29 PM" src="https://github.com/user-attachments/assets/02e76511-cb6a-4be9-ab5b-42237f75e203">

This section is going to require a lot more work.

**Comment by ktbolt** [comment]
I've now added a `Data File Format` section documenting the formats of 
- Text files used for boundary conditions and domain IDs
- VTK files for mesh, initial conditions and boundary conditions

<img width="1293" alt="Screenshot 2024-07-24 at 6 23 47 PM" src="https://github.com/user-attachments/assets/39fb9c29-a77a-4e2c-aa9c-4022ec614f74">

**Comment by ktbolt** [comment]
I'm now adding a bit of `Developer Guide` documentation.
<img width="1289" alt="Screenshot 2024-08-01 at 6 52 01 PM" src="https://github.com/user-attachments/assets/140502d1-1003-4e8c-91a7-b46f9c1d1f66">

**Comment by ktbolt** [comment]
I've added a `Code Organization` section documenting the organization of the files and such.
<img width="1442" alt="Screenshot 2024-08-02 at 5 36 36 PM" src="https://github.com/user-attachments/assets/5d229da3-3cad-4177-ba80-72c574cb899a">

**Comment by ktbolt** [comment]
I've added an `Implementation Details` section which covers some useful details of the well, implementation
<img width="1385" alt="imp-details" src="https://github.com/user-attachments/assets/acbd571f-13ba-468b-b93c-67846e9624d4">

In the `Flow of Control` section I outline the calling sequence and such of the program
<img width="1388" alt="flow" src="https://github.com/user-attachments/assets/a3cb077f-b16a-4c0b-96c4-524c3005951d">

and 

<img width="1383" alt="iterate" src="https://github.com/user-attachments/assets/607b9e9e-e1a0-40f7-a516-debcac8172ab">

**Comment by ktbolt** [comment]
I've added `Linear Algebra Interface` 

<img width="1384" alt="Screenshot 2024-08-12 at 2 35 47 PM" src="https://github.com/user-attachments/assets/3ad38b2d-5c2f-4aa6-8738-7540e6322237">

and `VTK Interface` implementation sections

<img width="1364" alt="Screenshot 2024-08-12 at 2 38 57 PM" src="https://github.com/user-attachments/assets/1e228f57-9ae9-4e3d-b9d5-78b95aa25192">

**Comment by ktbolt** [comment]
@MatteoSalvador @aabrown100-git @mrp089 @menon-karthik @dcodoni @zasexton @kharold23 @elenasmartinez @lpapamanolis @msbazzi I've finished all that I can do for the documentation. 

I now need people to 
- check for errors
- suggest any rewrite/reorganization 
- add docs for xml parameters that I couldn't explain, especially for electrophysiology
- write a theory section
- rewrite the `User Guide` sections; these were take from the svFSI docs

Clone the https://github.com/ktbolt/simvascular.github.io/tree/Add-svFSIplus-documentation_19 branch and have a look. 

I use [caddy](https://caddyserver.com/docs/install) to view the web pages
- install 
- cd to simvascular.github.io
- run `caddy file-server --listen  localhost:2015`

**Comment by ktbolt** [comment]
The core documentation is merged. There is lots more to do but each section can be its own Issue.
