### ISSUE TITLE
Missing GenBC demo on SimVascular website

### ISSUE THREAD

**Issue by JonathanPham** [SimVascular/simvascular.github.io#21]
### Description

The example project for the GenBC demo is missing on the website: https://simvascular.github.io/documentation/genbc.html

### Reproduction

Go to the website above.

### Expected behavior

The cylinder example project with GenBC should be available for download.

### Additional context

The example project is also referenced here: https://www.youtube.com/watch?v=znfV0XLV79s

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by ktbolt** [comment]
The documentation is there now.
