### ISSUE TITLE
information on industry consulting with SimVascular

### ISSUE THREAD

**Issue by alisonmarsden** [SimVascular/simvascular.github.io#24]
### Problem

I'd like to let people know that our team is available for outside consulting related to cardiovascular medical device design and evaluation.  Please add a section labeled "Industry Support" with text "The SimVascular team is available to aid industry partners via  independent consulting related to medical device design and evaluation as well as implementation of new software features.  Our team has experience performing finite element analysis for established and early stage industry partners including catheters, valves, stents, mechanical circulatory assist devices, and novel devices for pediatric cardiology"  
 

### Solution

Please add the section described above to the website.  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by ktbolt** [comment]
@alisonmarsden I've added an `Industry Support` section to the home page, right above the `Team` section. Or maybe it should go below the `Team` section or somewhere else, not sure.

<img width="1220" alt="Screenshot 2024-09-04 at 2 17 43 PM" src="https://github.com/user-attachments/assets/87397610-2bf6-4a66-a745-c2e481391d53">

**Comment by alisonmarsden** [comment]
Thanks – I think this should be moved below the team section, and also add at the end “Please contact Professor Marsden directly at ***@***.******@***.***> with inquiries.”



From: Dave Parker ***@***.***>
Date: Wednesday, September 4, 2024 at 11:22 PM
To: SimVascular/simvascular.github.io ***@***.***>
Cc: Alison Lesley Marsden ***@***.***>, Mention ***@***.***>
Subject: Re: [SimVascular/simvascular.github.io] information on industry consulting with SimVascular (Issue #24)

@alisonmarsden<https://github.com/alisonmarsden> I've added an Industry Support section to the home page, right above the Team section. Or maybe it should go below the Team section or somewhere else, not sure.
Screenshot.2024-09-04.at.2.17.43.PM.png (view on web)<https://github.com/user-attachments/assets/87397610-2bf6-4a66-a745-c2e481391d53>

**Comment by ktbolt** [comment]
@alisonmarsden I've made the changes you requested.

**Comment by ktbolt** [comment]
Merged and up.
