### ISSUE TITLE
Need to update the 0D Guide with the new BloodVessel element

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/simvascular.github.io#5]
The documentation for the 0D solver is outdated, due to the addition of the BloodVessel block, which replaced the following elements:

Resistor
RC
RL
RLC.
Need to update the 0D solver documentation.

@JonathanPham Has this been done?

**Comment by JonathanPham** [comment]
I think we should be good to close this issue now, @ktbolt!

**Comment by ktbolt** [comment]
Merged into the `main` branch.
