### ISSUE TITLE
Add developer guidelines to the website

### ISSUE THREAD

**Issue by alisonmarsden** [SimVascular/simvascular.github.io#8]
We need to a page to the website covering guidelines for developers and contributors to SimVascular.  This should include:  
1) code of conduct 
2) contribution guidelines

**Comment by mrp089** [comment]
I added the following Community Standards:
- [Code of conduct](https://github.com/SimVascular/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing guidelines](https://github.com/SimVascular/.github/blob/main/CONTRIBUTING.md)
- [Issue templates](https://github.com/SimVascular/.github/tree/main/.github/ISSUE_TEMPLATE)
- [Pull request template](https://github.com/SimVascular/.github/blob/main/.github/pull_request_template.md)
- [Introduction to SimVascular GitHub](https://github.com/SimVascular/.github/blob/main/profile/README.md)
- [License](https://github.com/SimVascular/.github/blob/main/LICENSE.md)

Please have a look, @alisonmarsden, @MatteoSalvador, @menon-karthik, @ktbolt. These are meant to be a first draft so we have something to start with. The files can be easily edited in the browser.

The files are all in a [separate .github repository](https://github.com/SimVascular/.github) within SimVascular. This way, all repositories default to those standards (but can overwrite them with their own).

All files are heavily inspired by BioDesign's [StanfordSpezi software project](https://github.com/StanfordSpezi) (with community files [here](https://github.com/StanfordSpezi/.github)). **Many thanks to @PSchmiedmayer for the inspiration and GitHub guidance!** 😄

**Comment by ktbolt** [comment]
@mrp089 You have got to be kidding!

**Comment by alisonmarsden** [comment]
It will be great to have these up on our website before the CZ software grant is due on Oct 17th.     This is one of the items they ask about.

From: Martin R. Pfaller ***@***.***>
Date: Friday, October 6, 2023 at 3:47 PM
To: SimVascular/simvascular.github.io ***@***.***>
Cc: Alison Lesley Marsden ***@***.***>, Mention ***@***.***>
Subject: Re: [SimVascular/simvascular.github.io] Add developer guidelines to the website (Issue #8)

I added the following Community Standards:

  *   Code of conduct<https://github.com/SimVascular/.github/blob/main/CODE_OF_CONDUCT.md>
  *   Contributing guidelines<https://github.com/SimVascular/.github/blob/main/CONTRIBUTING.md>
  *   Issue templates<https://github.com/SimVascular/.github/tree/main/.github/ISSUE_TEMPLATE>
  *   Pull request template<https://github.com/SimVascular/.github/blob/main/.github/pull_request_template.md>
  *   Introduction to SimVascular GitHub<https://github.com/SimVascular/.github/blob/main/profile/README.md>
  *   License<https://github.com/SimVascular/.github/blob/main/LICENSE.md>

Please have a look, @alisonmarsden<https://github.com/alisonmarsden>, @MatteoSalvador<https://github.com/MatteoSalvador>, @menon-karthik<https://github.com/menon-karthik>, @ktbolt<https://github.com/ktbolt>. These are meant to be a first draft so we have something to start with. The files can be easily edited in the browser.

The files are all in a separate .github repository<https://github.com/SimVascular/.github> within SimVascular. This way, all repositories default to those standards (but can overwrite them with their own).

All files are heavily inspired by BioDesign's StanfordSpezi software project<https://github.com/StanfordSpezi> (with community files here<https://github.com/StanfordSpezi/.github>). Many thanks to @PSchmiedmayer<https://github.com/PSchmiedmayer> for the inspiration and GitHub guidance! 😄

**Comment by ktbolt** [comment]
I will rewrite the `Contributing Guidelines` , get rid of all this
```
The keywords "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in [RFC 2119]
```

and remove all of the words using all capital letters like `MUST` below
```
You MUST follow our [Code of Conduct](https://github.com/SimVascular/.github/blob/main/CODE_OF_CONDUCT.md).
```

writing in all capital letters is like shouting

**Comment by MatteoSalvador** [comment]
Thanks @mrp089! I went through all the community standards. I just have a few suggestions for the moment:
- **Issue templates:** it might be useful to give the possibility to the user to attach several types of files (pictures, scripts, meshes, `XML` configurations) in order to ease the bug fixing process.
- **Pull request templates:** I would clearly state that adding tests for each new feature implemented is mandatory. I would also mention the importance of code coverage during testing, which should ideally always increase after any PR.
- **License:** I have always reported this type of MIT license at the beginning of each `.h`/`.cpp` file. I am particularly referring to the sentence 
> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

I am of course happy to keep discussing this!

**Comment by menon-karthik** [comment]
This looks like a really great first draft @mrp089, thanks for doing this! 

I noticed some things were not clear (like "Github flow" linking to the general github documentation) and a few typos in the `Contributing Guidelines`. Should the rest of us fork/edit/merge the usual way or does this repository work differently?

About the issue and pull request templates, this is probably just me being dumb, but it's not clear to me how this actually works. When a new pull request/issue is created does it automatically open up in the specified template format for the user or does a user have to do something to get that format? If the latter, maybe we should provide instructions.

I like @MatteoSalvador's idea about adding specific instructions for tests and code coverage, but I also think we should actually enforce it by using Doxygen to prevent merging undocumented code. And mention that we are doing this in the instructions. See discussion [here](https://github.com/StanfordCBCL/svZeroDPlus/issues/46). What does everyone else think?

**Comment by mrp089** [comment]
Thank you very much for the constructive feedback, @MatteoSalvador and @menon-karthik! I'll add my replies below. I'm closing this issue so we can continue the discussion in https://github.com/SimVascular/.github.

@alisonmarsden, I've added a brief `Contributing` section to the SimVascular homepage and linked the Contributing Guidelines and the Code of Conduct (#10).

**Comment by mrp089** [comment]
> * **Issue templates:** it might be useful to give the possibility to the user to attach several types of files (pictures, scripts, meshes, `XML` configurations) in order to ease the bug fixing process.

Great idea, please add!

> * **Pull request templates:** I would clearly state that adding tests for each new feature implemented is mandatory. I would also mention the importance of code coverage during testing, which should ideally always increase after any PR.

Also great idea, please add!

> * **License:** I have always reported this type of MIT license at the beginning of each `.h`/`.cpp` file. I am particularly referring to the sentence
> 
> > The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
> 
> I am of course happy to keep discussing this!

Happy to discuss in https://github.com/SimVascular/.github!

**Comment by mrp089** [comment]
> I noticed some things were not clear (like "Github flow" linking to the general github documentation) and a few typos in the `Contributing Guidelines`. Should the rest of us fork/edit/merge the usual way or does this repository work differently?

Yes, please!

> About the issue and pull request templates, this is probably just me being dumb, but it's not clear to me how this actually works. When a new pull request/issue is created does it automatically open up in the specified template format for the user or does a user have to do something to get that format? If the latter, maybe we should provide instructions.

They come up now when you open a new issue or pull request. You can give it a try and just click through it without adding anything.

> I like @MatteoSalvador's idea about adding specific instructions for tests and code coverage, but I also think we should actually enforce it by using Doxygen to prevent merging undocumented code. And mention that we are doing this in the instructions. See discussion [here](https://github.com/StanfordCBCL/svZeroDPlus/issues/46). What does everyone else think?

I'm all for it! Unfortunately, we have ~1500 Doxygen warning in `svFSI+` so we can't do that anytime soon. But we could try implementing something that the number of warnings must go down in every pull request.

We could do the same for coverage. [StanfordSpezi uses Codecov](https://app.codecov.io/gh/StanfordSpezi/Spezi), which @MatteoSalvador and I briefly looked into. However, it's only free for public repositories (`svFSI+` is still private).
