### ISSUE TITLE
Move svFSI documentation to svFSI+ repository

### ISSUE THREAD

**Issue by mrp089** [SimVascular/simvascular.github.io#9]
I'll move the `svfsi` folder to the [svFSI+](https://github.com/SimVascular/svFSIplus) repository (see https://github.com/SimVascular/svFSIplus/issues/110) to keep the documentation with the code.

First, I'll add the files to the [svFSI+ documentation folder](https://github.com/SimVascular/svFSIplus/tree/main/Documentation/pages) and include them in the Doxygen HTML build. Second, I will delete the files from this repository and include a link to the new documentation on the main page.

**Comment by ktbolt** [comment]
I think this has been completed.
